apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: ismail19/udagram-api-user:latest
        ports:
        - containerPort: 8080
        envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
        resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m